 export const taxRates = [
    { state: 'Alabama', rate: 4.00 },
    { state: 'Alaska', rate: 0.00 },
    { state: 'Arizona', rate: 5.60 },
    { state: 'Arkansas', rate: 6.50 },
    { state: 'California', rate: 7.25 },
    { state: 'Colorado', rate: 2.90 },
    { state: 'Connecticut', rate: 6.35 },
    { state: 'Delaware', rate: 0.00 },
    { state: 'Florida', rate: 6.00 },
    { state: 'Georgia', rate: 4.00 },
    { state: 'Hawaii', rate: 4.00 },
    { state: 'Idaho', rate: 6.00 },
    { state: 'Illinois', rate: 6.25 },
    { state: 'Indiana', rate: 7.00 },
    { state: 'Iowa', rate: 6.00 },
    { state: 'Kansas', rate: 6.50 },
    { state: 'Kentucky', rate: 6.00 },
    { state: 'Louisiana', rate: 4.45 },
    { state: 'Maine', rate: 5.50 },
    { state: 'Maryland', rate: 6.00 },
    { state: 'Massachusetts', rate: 6.25 },
    { state: 'Michigan', rate: 6.00 },
    { state: 'Minnesota', rate: 6.88 },
    { state: 'Mississippi', rate: 7.00 },
    { state: 'Missouri', rate: 4.23 },
    { state: 'Montana', rate: 0.00 },
    { state: 'Nebraska', rate: 5.50 },
    { state: 'Nevada', rate: 6.85 },
    { state: 'New Hampshire', rate: 0.00 },
    { state: 'New Jersey', rate: 6.63 },
    { state: 'New Mexico', rate: 4.88 },
    { state: 'New York', rate: 4.00 },
    { state: 'North Carolina', rate: 4.75 },
    { state: 'North Dakota', rate: 5.00 },
    { state: 'Ohio', rate: 5.75 },
    { state: 'Oklahoma', rate: 4.50 },
    { state: 'Oregon', rate: 0.00 },
    { state: 'Pennsylvania', rate: 6.00 },
    { state: 'Rhode Island', rate: 7.00 },
    { state: 'South Carolina', rate: 6.00 },
    { state: 'South Dakota', rate: 4.20 },
    { state: 'Tennessee', rate: 7.00 },
    { state: 'Texas', rate: 6.25 },
    { state: 'Utah', rate: 6.10 },
    { state: 'Vermont', rate: 6.00 },
    { state: 'Virginia', rate: 5.30 },
    { state: 'Washington', rate: 6.50 },
    { state: 'West Virginia', rate: 6.00 },
    { state: 'Wisconsin', rate: 5.00 },
    { state: 'Wyoming', rate: 4.00 },
    { state: 'D.C.', rate: 6.00 }
   ];
   